#%RAML 1.0
title: 安全业务审批系统
version: v1
baseUri: http://127.0.0.1:8083/
protocols:
  - http

/system/org/list:
  post:
    queryParameters:
      id: integer
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              key:
